# Generated by Django 3.1.2 on 2020-12-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rut', models.CharField(max_length=10)),
                ('Nombres', models.CharField(max_length=50)),
                ('Correo', models.EmailField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
                ('Asunto', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
