# Generated by Django 3.1.3 on 2020-12-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20201219_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Imagen', models.TextField()),
                ('Precio', models.CharField(max_length=15)),
            ],
        ),
    ]
